### ISSUE TITLE
Reflector "Temporary failure in name resolution" failed build

### ISSUE THREAD

**Issue by ghost** [arcolinux/arcolinuxl-iso#13]
ISO build fails at the following:
```
function getNewMirrorCleanAndUpgrade() {
    reflector --protocol https --latest 50 --number 20 --sort rate --save /etc/pacman.d/mirrorlist
    pacman -Sc --noconfirm
    pacman -Syyu --noconfirm
}
```
With this message:

**error: failed to retrieve mirror data: (<urlopen error [Errno -3] Temporary failure in name resolution>)**

**Comment by arcolinuxz** [comment]
means you do not have internet.
Dns issues ?

**Comment by arcolinuxz** [comment]
or is reflector not installed

**Comment by ghost** [comment]
Internet works fine and my host /etc/resolv.conf sounds normal. Everything gets downloaded during the build process, but only reflector mirror selecting fails. Yes, reflector is installed too!

**Comment by arcolinuxz** [comment]
try again now

**Comment by arcolinuxz** [comment]
why don't you join me on discord easier and faster to communicate

**Comment by ghost** [comment]
Same results ... what I did instead was I actually edited **build.sh** and replaced this line:
`curl -o ${work_dir}/${arch}/airootfs/etc/pacman.d/mirrorlist 'https://www.archlinux.org/mirrorlist/?country=all&protocol=http&use_mirror_status=on'`

with:
`reflector --protocol https --latest 30 --number 20 --sort rate --save ${work_dir}/x86_64/airootfs/etc/pacman.d/mirrorlist`

Remember to add **_reflector_** in the packages line in **build.sh** above that line.

This way the ISO build successfully with custom mirrors!

Also, how to join you guys on discord?

**Comment by arcolinuxz** [comment]
Thanks

discord is here at bottom of page :
https://arcolinux.info/arcolinux-editions/

Erik
