### ISSUE TITLE
Calamares - install fails

### ISSUE THREAD

**Issue by ghost** [arcolinux/arcolinuxl-iso#15]
![383c2b51-75e5-47c8-b142-d2886b211d5e](https://user-images.githubusercontent.com/6697859/51706444-bb00a480-201e-11e9-9c6b-189fe0cc307e.jpeg)

Boost python fails 
Unmet dependencies

The install job does not finish.

Hope the error message in the image helps.

**Comment by arcolinuxz** [comment]
Post it on the the forum
There is a forum just for calamares stuff

I need to know what iso this is?
Did you create the iso?
etc...

Cheers
erik

**Comment by arcolinuxz** [comment]
it means one or other package was not available to remove it - probably
