### ISSUE TITLE
Installing ArcoLinux 19.03 with disk encryption enabled leaves system unbootable

### ISSUE THREAD

**Issue by ghost** [arcolinux/arcolinuxl-iso#16]
Version 19.03

After selecting the option to encrypt the system during installation, the system is left unbootable. Instead, Grub shows an `error: unknown device: <uuid>` message.

I have seen this on two different machines. I just tried the same in VirtualBox on my primary laptop and got the same error. If I choose to not encrypt the system during installation, there are no issues during boot.

**Comment by arcolinuxz** [comment]
we know

encryption is not possible yet

cheers
Erik
