### ISSUE TITLE
Boot fails after clean install v19.06.1-x84_64

### ISSUE THREAD

**Issue by seemsindie** [arcolinux/arcolinuxl-iso#17]
I got this after booting into system

![image](https://user-images.githubusercontent.com/1268576/60762273-0900e600-a05c-11e9-81b7-95e991e038ba.png)

Install went ok, and I clicked "restart now" and I got that.

**Comment by arcolinuxz** [comment]
I wonder if you can benefit from our LTS version that we have just launched.

Download one of the iso's with the letters LTS in them

https://bike.seedhost.eu/arcolinux/aag/

More info here

https://arcolinux.info/arcolinux-launches-a-new-project-lts-kernel-or-long-term-support-kernel/

**Comment by seemsindie** [comment]
Yes, LTS is running fine just having an issue installing Nvidia drivers.

EDIT: I had to install nvidia-lts because of LTS... :)

Thanks
