### ISSUE TITLE
Better rename "Package selection" into "Packages" (calamares installer)

### ISSUE THREAD

**Issue by sxiii** [arcolinux/arcolinuxl-iso#21]
In some small display resolutions, like virtualbox default 800x600 one, we will see this:

![image](https://user-images.githubusercontent.com/575925/74658317-4d2b9b80-5192-11ea-9b44-1cec49d13457.png)

Which is not cool.

Can be solved by replacing tab called "Package selection" to just "Packages"; which will not loose the meaning but will be more in the style with other parts of calamares installer.

**Comment by arcolinuxz** [comment]
We can not change that.
Set your virtualbox the right way and depending of your screen it will adapt to your screen resolution.
Lots of videos that tell you how that is done.

**Comment by sxiii** [comment]
Strange, I bet it's possible to change everything as we do have the source code... And I was just waiting for some graphical candy-ness. Ok. Nevermind...
