### ISSUE TITLE
Provide VLC package by default and some browsers

### ISSUE THREAD

**Issue by sxiii** [arcolinux/arcolinuxl-iso#22]
I can't find VLC package in the installer. VLC is one of the most popular audio-video player out there. Pretty sure it should be there. Along with some browsers:
* Firefox
* Chromium
* Vivaldi
* Opera
* Pale moon
All of them are supported in Arch either via pacman or AUR.

**Comment by arcolinuxz** [comment]
they are already on the isos
just not palemoon
you will have to install it after clean install.
IF your app is not in the list it might still be installed 
IF the app is a default app that is always going to be installed like firefox you will not see it in the list

**Comment by sxiii** [comment]
Yeah; I was saying only about the "calamares" installer. That it does not include them. That's it. And I was unable to install acrolinux anyway (look at the issue #23)
