### ISSUE TITLE
Different installation errors while trying to install in Virtualbox

### ISSUE THREAD

**Issue by sxiii** [arcolinux/arcolinuxl-iso#23]
First error I didn't screenshooted; but the second one is this:

![image](https://user-images.githubusercontent.com/575925/74660422-65051e80-5196-11ea-8162-caac8462050f.png)

Maybe this is out of space error? I've used 8 gb disk as default recommended by virtualbox.

**Comment by arcolinuxz** [comment]
no space left
sound clear what you should do
