### ISSUE TITLE
Calamares Not Working

### ISSUE THREAD

**Issue by Opencode-foss** [arcolinux/arcolinuxl-iso#24]
I tried installing ArcoLinux in Virt-Manager with one core and Calamares would not open when I pushed the run Calamares button. When I used two cores it worked this seems to be a bug to me because using one core usually works with other distros using Calamares. This is also a problem in ArcoLinuxd.

**Comment by arcolinuxz** [comment]
calamares needs two cores to run - we have advertised this on the discord channel
