### ISSUE TITLE
Feature Request: If you check off one display manager, it will install and enable the selected display manager.

### ISSUE THREAD

**Issue by trymeouteh** [arcolinux/arcolinuxl-iso#25]
If you check off one or more display manager, it will install and enable the first selected display manager. This way whn you install ArcoLinux as you like, the first selected display manager will be enabled and no need to change the display manager.

**Comment by arcolinuxz** [comment]
it does that
just gnome or gdm is tricky as it wants to put wayland as backend and virtualbox and wayland do not go together at this point in time

**Comment by trymeouteh** [comment]
I also find that it will not apply LightDM when I select Cinnamon or Xfce as a DE. Is this also only happening in virtualbox?

**Comment by arcolinuxz** [comment]
with 28 isos you will have to tell with which one you start 
I will have a go at it

**Comment by trymeouteh** [comment]
I am using "arcolinuxb-awesome-v21.09.11-x86_64.iso"

**Comment by arcolinuxz** [comment]
I remember we removed it because of issues reported by users
now it is a manual "tolightdm" alias
and we are sure sddm works as we test that one all the time

**Comment by arcolinuxz** [comment]
https://github.com/arcolinux/arcolinuxl-iso/blob/master/archiso/airootfs/usr/local/bin/arcolinux-displaymanager-check

**Comment by trymeouteh** [comment]
To my understanding all the other display mangers in the scripts are commented out except for sddm due to issues.

Will this be fixed in the future by chance?

I would also like to suggest choosing the display manager on the same page of the installer where you choose the desktop. This way if you choose GNOME, you can click on the button to open the packages that are installed with GNOME and choose to uncheck GDM and choose a different display manger to go along with your desktop instead of having a desktop page and a login display page.
