### ISSUE TITLE
When you dont check off automatic login to main users account, it will not install/launch your desktop environment

### ISSUE THREAD

**Issue by trymeouteh** [arcolinux/arcolinuxl-iso#26]
I am using "arcolinuxb-awesome-v21.09.11-x86_64.iso" and when I install Arco with any desktop environment, once I have installed Arco and boot up into the distro, if I do not check off the automatic login box when I create my main user, it will not boot up or maybe not even install my desktop environment I selected and instead boot up into the same desktop that comes in the ISO when you boot up the ISO.

**Comment by arcolinuxz** [comment]
that is quite normal.
Change the login yourself.
If you don't use autologin, you choose the desktop in SDDM
If you do use autologin, we tell SDDM to login to Xfce on ArcoLinuxL or xS ...
On the B isos we will tell SDDM to autologin into Awesome if you use ArcoLinuxB Awesome etc ...
There is no ai present in Calamares and there never will be.
What desktop to login into if you install 10 of them?

Extra desktops will only be installed if you have an internet connection.

**Comment by trymeouteh** [comment]
It maybe normal but not user friendly. A suggestion would be to select the first desktop alphabetically or you will choose the default desktop if you choose to install two or more desktops.

Another suggestion will be to have the default arco desktop to have a button/menu on the welcome to arco linux window where you can change your desktop using a GUI
