### ISSUE TITLE
pkglist.x86_64.txt': No such file or directory

### ISSUE THREAD

**Issue by ghost** [arcolinux/arcolinuxl-iso#27]
Moving pkglist.x86_64.txt
########################
cp: cannot stat '/home/archkubi/arcolinux-build/iso/arch/pkglist.x86_64.txt': No such file or directory

##################################################################
Phase 9 :
- Making sure we start with a clean slate next time                                                                     
##################################################################                                                      

Deleting the build folder if one exists - takes some time

##################################################################
DONE
- Check your out folder :/home/archkubi/ArcoLinux-Out                                                                   
##################################################################

**Comment by arcolinuxz** [comment]
search for the first issue

**Comment by ghost** [comment]
################################################################## 
Phase 1 : 
- Setting General parameters
################################################################## 

################################################################## 
Building the desktop                   : xfce
Building version                       : v22.05.01
Iso label                              : arcolinuxd-v22.05.01-x86_64.iso
Do you have the right archiso version? : archiso 62.1-1
What is the required archiso version?  : archiso 62.1-1
Build folder                           : /root/arcolinuxd-build
Out folder                             : /root/ArcoLinuxD-Out
################################################################## 
##################################################################
Archiso has the correct version. Continuing ...
##################################################################

################################################################## 
Phase 2 :
- Checking if archiso is installed
- Saving current archiso version to readme
- Making mkarchiso verbose
################################################################## 

Archiso is already installed

Saving current archiso version to readme

Making mkarchiso verbose

################################################################## 
Phase 3 :
- Deleting the build folder if one exists
- Copying the Archiso folder to build folder
##################################################################                                                   

Deleting the build folder if one exists - takes some time

Copying the Archiso folder to build work


################################################################## 
Phase 4 :
- Deleting any files in /etc/skel                                                                                    
- Getting the last version of bashrc in /etc/skel                                                                    
- Removing the old packages.x86_64 file from build folder                                                            
- Copying the new packages.x86_64 file to the build folder                                                           
- Add our own personal repo + add your packages to packages-personal-repo.x86_64                                     
##################################################################                                                   

Deleting any files in /etc/skel

Getting the last version of bashrc in /etc/skel

--2022-04-17 13:50:17--  https://raw.githubusercontent.com/arcolinux/arcolinux-root/master/etc/skel/.bashrc-latest
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11785 (12K) [text/plain]
Saving to: ‘/root/arcolinuxd-build/archiso/airootfs/etc/skel/.bashrc’

/root/arcolinuxd-build/archis 100%[==============================================>]  11.51K  --.-KB/s    in 0.004s  

2022-04-17 13:50:18 (2.68 MB/s) - ‘/root/arcolinuxd-build/archiso/airootfs/etc/skel/.bashrc’ saved [11785/11785]

Removing the old packages.x86_64 file from build folder

Copying the new packages.x86_64 file to the build folder


################################################################## 
Phase 5 : 
- Changing all references                                                                                            
- Adding time to /etc/dev-rel                                                                                        
##################################################################                                                   

Changing all references

Adding time to /etc/dev-rel
Iso build on : Sun Apr 17 01:50:18 PM +03 2022

###########################################################
Phase 6 :
- Cleaning the cache from /var/cache/pacman/pkg/                                                                     
###########################################################                                                          

Cleaning the cache from /var/cache/pacman/pkg/

Cache directory: /var/cache/pacman/pkg/
:: Do you want to remove ALL files from cache? [y/N] y
removing all files from cache...

Database directory: /var/lib/pacman/
:: Do you want to remove unused repositories? [Y/n] y
removing unused sync repositories...

################################################################## 
Phase 7 :
- Building the iso - this can take a while - be patient                                                              
##################################################################                                                   

[mkarchiso] INFO: Validating options...
[mkarchiso] INFO: Done!
[mkarchiso] INFO: mkarchiso configuration settings
[mkarchiso] INFO:              Architecture:   x86_64
[mkarchiso] INFO:         Working directory:   /root/arcolinuxd-build
[mkarchiso] INFO:    Installation directory:   arch
[mkarchiso] INFO:                Build date:   2022-04-17T13:50+0300
[mkarchiso] INFO:          Output directory:   /root/ArcoLinuxD-Out
[mkarchiso] INFO:        Current build mode:   iso
[mkarchiso] INFO:               Build modes:   iso
[mkarchiso] INFO:                   GPG key:   None
[mkarchiso] INFO:                GPG signer:   None
[mkarchiso] INFO: Code signing certificates:   None
[mkarchiso] INFO:                   Profile:   /root/arcolinuxd-build/archiso
[mkarchiso] INFO: Pacman configuration file:   /root/arcolinuxd-build/archiso/pacman.conf
[mkarchiso] INFO:           Image file name:   arcolinuxd-v22.05.01-x86_64.iso
[mkarchiso] INFO:          ISO volume label:   arcolinuxd-v22.05.01
[mkarchiso] INFO:             ISO publisher:   ArcoLinux <http://www.arcolinux.info>
[mkarchiso] INFO:           ISO application:   ArcoLinux Live/Rescue CD
[mkarchiso] INFO:                Boot modes:   bios.syslinux.mbr bios.syslinux.eltorito uefi-x64.systemd-boot.esp uefi-x64.systemd-boot.eltorito
[mkarchiso] INFO:             Packages File:   /root/arcolinuxd-build/archiso/packages.x86_64
[mkarchiso] INFO:                  Packages:   alsa-utils amd-ucode arch-install-scripts base bind-tools broadcom-wl-dkms btrfs-progs clonezilla cryptsetup ddrescue dhclient diffutils dmraid dnsmasq dosfstools e2fsprogs edk2-shell efibootmgr ethtool exfatprogs f2fs-tools fatresize fsarchiver gnu-netcat gpart gpm gptfdisk grub hdparm intel-ucode ipw2100-fw ipw2200-fw irssi jfsutils less libfido2 libusb-compat linux linux-atm linux-firmware linux-firmware-qlogic linux-firmware-marvell lsscsi lvm2 man-db man-pages mc mdadm memtest86+ mkinitcpio mkinitcpio-archiso mkinitcpio-nfs-utils modemmanager mtools nano nbd ndisc6 nfs-utils nilfs-utils ntfs-3g nvme-cli openconnect openssh openvpn partclone parted partimage pcsclite ppp pptpclient pv qemu-guest-agent refind reflector reiserfsprogs rp-pppoe rsync rxvt-unicode-terminfo screen sdparm sg3_utils smartmontools sof-firmware squashfs-tools sudo syslinux tcpdump terminus-font testdisk tmux tpm2-tss udftools usb_modeswitch usbmuxd usbutils vim vpnc wireless-regdb wireless_tools wpa_supplicant wvdial xfsprogs xl2tpd aic94xx-firmware dialog dnsutils linux-headers logrotate ntp r8168-dkms upd72020x-fw wd719x-firmware wget xorg-server xorg-apps xorg-xinit xf86-input-elographics xf86-input-evdev xf86-input-libinput xf86-input-vmmouse xf86-input-void xf86-video-amdgpu xf86-video-ati xf86-video-fbdev xf86-video-nouveau xf86-video-openchrome xf86-video-vesa xf86-video-vmware mesa nvidia-dkms nvidia-utils nvidia-settings mesa-utils base base-devel open-vm-tools virtualbox-guest-utils os-prober cryptsetup mobile-broadband-provider-info modemmanager networkmanager network-manager-applet networkmanager-openconnect networkmanager-openvpn networkmanager-pptp networkmanager-vpnc openresolv xdg-user-dirs numlockx termite noto-fonts ttf-dejavu ttf-hack arc-gtk-theme arandr asciinema bash-completion bat dex duf-bin edid-decode-git expac git gksu gparted hw-probe laptop-detect lsb-release mlocate pkgfile polkit polkit-gnome ripgrep rxvt-unicode bibata-cursor-theme-bin sardi-icons surfn-icons-git mkinitcpio-openswap alacritty appstream neofetch paru-bin rate-mirrors-bin the_silver_searcher urxvt-fullscreen urxvt-perls urxvt-resize-font-git yay-bin arcolinux-alacritty-git arcolinux-grub-theme-vimix-git arcolinux-gtk3-sardi-arc-git arcolinux-keyring arcolinux-mirrorlist-git arcolinux-neofetch-git arcolinux-paru-git arcolinuxd-system-config-git arcolinux-systemd-services-git arcolinux-wallpapers-git arcolinux-xfce-git arco-calamares arcolinux-system-installation-git arcolinuxd-config-live-session-git arcolinuxd-welcome-app-git ckbcomp upower kcoreaddons kconfig ki18n kservice kwidgetsaddons kpmcore boost-libs libpwquality squashfs-tools plasma-framework hwinfo qt5-xmlpatterns adobe-source-han-sans-jp-fonts adobe-source-han-sans-kr-fonts adobe-source-han-sans-cn-fonts arcod-calamares-config-git accountsservice sddm arcolinux-sddm-simplicity-git exo thunar xfce4-panel xfce4-session xfce4-settings xfdesktop xfwm4 chaotic-keyring
error: config file /etc/pacman.d/arcolinux-mirrorlist could not be read: No such file or directory
error parsing '/root/arcolinuxd-build/archiso/pacman.conf'
[mkarchiso] INFO: Copying custom pacman.conf to work directory...
[mkarchiso] INFO: Using pacman CacheDir: 
error: config file /etc/pacman.d/arcolinux-mirrorlist could not be read: No such file or directory
error parsing '/root/arcolinuxd-build/archiso/pacman.conf'
[mkarchiso] INFO: Copying custom airootfs files...
[mkarchiso] INFO: Done!
[mkarchiso] INFO: Installing packages to '/root/arcolinuxd-build/x86_64/airootfs/'...
==> Creating install root at /root/arcolinuxd-build/x86_64/airootfs
==> Installing packages to /root/arcolinuxd-build/x86_64/airootfs
error: no usable package repositories configured.
==> ERROR: Failed to install packages to new root

###################################################################
Phase 8 :
- Creating checksums                                                                                                 
- Copying pgklist                                                                                                    
###################################################################                                                  

Creating checksums for : arcolinuxd-v22.05.01-x86_64.iso
##################################################################

Building sha1sum
########################
sha1sum: arcolinuxd-v22.05.01-x86_64.iso: No such file or directory
Building sha256sum
########################
sha256sum: arcolinuxd-v22.05.01-x86_64.iso: No such file or directory
Building md5sum
########################
md5sum: arcolinuxd-v22.05.01-x86_64.iso: No such file or directory

Moving pkglist.x86_64.txt
########################
cp: cannot stat '/root/arcolinuxd-build/iso/arch/pkglist.x86_64.txt': No such file or directory

##################################################################
Phase 9 :
- Making sure we start with a clean slate next time                                                                  
##################################################################                                                   

Deleting the build folder if one exists - takes some time

##################################################################
DONE
- Check your out folder :/root/ArcoLinuxD-Out                                                                        
##################################################################

**Comment by arcolinuxz** [comment]
did you find it ?

I did 

ps do not start the script with sudo 

just 

./40 ...

ps make a post on the arcolinux forum
that is where you should ask things like that

**Comment by ghost** [comment]
my english not good sorry 
ı start now ./30 ... not change
ı don't know how ı fix this ı search but cant find
https://youtu.be/jS4FD98PST0

**Comment by arcolinuxz** [comment]
I see you on the 

https://arcolinuxforum.com

**Comment by arcolinuxz** [comment]
use deepl  to translate from your language to English
