### ISSUE TITLE
Arco Linux XL questions/ideas for future versions.

### ISSUE THREAD

**Issue by kingdotIO** [arcolinux/arcolinuxl-iso#29]
When I think XL I think everything is included, including the kitchen sink, I have a few recommendations seeing as my ideas are plenty but skill to implement them is basic at best, ArchZFS I would think would be a give in to include, unfortunately it's not as of the latest release, 8/30 I believe but some say 9/4, Endeavor and Gods joke to the Linux Community... aka Ubuntu both include it as a Calamares option, secondly, I love customizing my setup, I use Serlent-LRW-Benbi:Blake3 in most cases, I also mount Btrfs subvolumes directly, however I despise the configuration, eg. Manually editing the conf files, and that's why I love Arco, but the setup is obviously not my choice, is there any possibility of adding a stopgap or bridge so you can do your little customization but still get the full effect of being a kid in a candy shop selecting each and every package because the installer for calamares is amazing and so easy, ABIF I know while not readily maintained, allows some freedom, is there any way of adding it in addition to Calamares, similar to Archcraft or ArchLabs?

**Comment by arcolinuxz** [comment]
read it

**Comment by kingdotIO** [comment]
Read it? Read what? I'm lost lol.

Bugs I've noticed as well on standard install at random, if I report them can I get an XL beta iso now? Whatever you got I'm interested as long as it's XL or B-Xtended, as they are my favorites...pretty please? Lmfao

There's a bug that could be ironed out, installing the way you intended still periodically crashes, all surounding the mount point Calamares assigns for install...it doesn't unmount sometimes messing up the grub or post config portion of the installer, and more than twice the entire /tmp MP freezes (on flash storage for certain idk about hard disks) and if it helps you, I always go Btrfs for calamares auto installs.

Btrfs misses subvolumes possible, opt,run, tmp, var, s/bin, lib/32/64 could all be subvolumes and when I edit etc/Calamares to include those, I don't have any issues with 
The problem MPs tmp, lib, run, opt which sometimes can crash the installer with regular physical volumes.

On install crash, booting the iso breaks whatever you selected on boot eg. Nvidia breaks the Nvidia option, opensource breaks opensource, and even removing the iso doesn't help, the only fix I found was booting a different option then running Pacman & updating the mirror list, otherwise it soft breaks causing the package key bug that you eliminated for the most part, I test installs alot so I see more than average users trying Arco out might.

**Comment by arcolinuxz** [comment]
not interested for now
