### ISSUE TITLE
Locale.conf

### ISSUE THREAD

**Issue by arcolinuxz** [arcolinux/arcolinuxl-iso#3]
Changing the language in calamares does not end up with all lines in /etc/locale.conf with that language

first line is correct 
rest is set in English
Gives issues in the clock/calendar.

**Comment by arcolinuxz** [comment]
Swagarch does not seem to have this issue

**Comment by ghost** [comment]
Understand the problem, I will look into this

**Comment by archmerge** [comment]
no problem at all - setting in calamares on one of the screens has been skipped - set it right on the installation screen of calamares

**Comment by arcolinuxz** [comment]
No problem at all - do not skip setting screen in calamares - set locale
