### ISSUE TITLE
/efiboot/loader/entries have wrong filenames which breaks builds for all arcolinuxb builds

### ISSUE THREAD

**Issue by coddiw0mple** [arcolinux/arcolinuxl-iso#30]
The files in archiso/efiboot/loader/entries are named as: 
```
01-archiso-x86_64-linux.conf
02-archiso-x86_64-linux-no-nouveau.conf
03-nvidianouveau.conf
04-nvidianonouveau.conf
05-nomodeset.conf
```

Whereas the scripts for all arcolinuxb builds need them to be named as:
```
1-archiso-x86_64-linux.conf
2-archiso-x86_64-linux-no-nouveau.conf
3-nvidianouveau.conf
4-nvidianonouveau.conf
5-nomodeset.conf
```

I don't know if this will break something else but for all the arcolinuxb install scripts I checked, we use the 1,2,3... notation instead of the 01,02,03,.... notation

**Comment by arcolinuxz** [comment]
does not break a thing
and the files are not used anymore
I suppose at some time Arch will remove them 
at which point
so will I

**Comment by coddiw0mple** [comment]
These files are still used in arcolinuxb iso builds. 

https://github.com/arcolinuxb/arco-awesome/blob/master/installation-scripts/30-build-the-iso-the-first-time.sh

Check lines 264-268

I'll retry the entire process and let you know, for some reason it broke for me.
