### ISSUE TITLE
Calamares does not start

### ISSUE THREAD

**Issue by ajaybhatia** [arcolinux/arcolinuxl-iso#6]
Hey I cloned the repo and build the iso. The problem is that Calamares installers fails to autostart for liveuser. Due to this reason I'm unable to install the distro on neither VM or real disk. Same is the case with arcolinuxd-iso repo.

**Comment by arcolinuxz** [comment]
With each new kernel we will need to make a new calamares. That is something we need to think about when launching the BYOI project... 
That is what you need to do.

**Comment by ajaybhatia** [comment]
Thank you very much! Should I pull the calamares from your repos to make the iso?

**Comment by arcolinuxz** [comment]
testing it now myself

**Comment by arcolinuxz** [comment]
Bad news - Just build ArcoLinuxD - calamares opens - installing now 
![calamares](https://user-images.githubusercontent.com/36679406/37116746-6fe34264-224f-11e8-882b-1f2bc82ce014.png)

**Comment by ajaybhatia** [comment]
Have you just rebuild the iso without touching calamares?

**Comment by arcolinuxz** [comment]
Yes I have - tutorials will follow after 1st April

**Comment by ajaybhatia** [comment]
Got it!
