### ISSUE TITLE
Packages.both improvement : qt4 can be left out?

### ISSUE THREAD

**Issue by erikdubois** [arcolinux/arcolinuxl-iso#7]
Test it out - seems to be the case

https://arcolinuxforum.com/viewtopic.php?f=45&t=395&sid=0b06c9061539575a154b02e972d209cf

**Comment by arcolinuxz** [comment]
pacman -Sii qt

`Required By     : ams  attica-qt4  automoc4  chinese-calendar  clementine  fbreader
                  fcitx-qt4  freecad  freemat  gambas3-gb-qt4  gebabbel  hedgewars
                  hydrogen  ibus-qt  keepassx  keepassx2  launchy  libdbusmenu-qt4
                  libechonest  liblastfm  liblightdm-qt4  licq  lmms  mixxx  mumble
                  murmur  openssh-askpass  ophcrack  phonon-qt4  polkit-qt4  poppler-qt4
                  projectm-qt  pyqt4-common  pyside-tools-common  python-pyside
                  python-shiboken  python2-pyside  python2-shiboken  qca-qt4  qconf
                  qimageblitz  qjson  qmpdclient  qscintilla-qt4  qsopcast
                  qt-assistant-compat  qtcurve-qt4  qtscriptgenerator  qwt5  qwtplot3d
                  scribus  shiboken  soqt  tipp10  tuxcards  v4l2ucp  x2goclient
                  x2goplugin
`

**Comment by arcolinuxz** [comment]
testing now since 6.6.2
